version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

  tainacan:
    depends_on:
      - wordpress
    image: tainacan/wordpress:latest
    restart: always
    environment:
      TAINACAN_DATABASE_HOST: db
      TAINACAN_DATABASE_NAME: wordpress
      TAINACAN_DATABASE_USER: wordpress
      TAINACAN_DATABASE_PASSWORD: wordpress
      TAINACAN_WP_URL: http://wordpress

volumes:
  db_data:
