version: "3.8"

services:
  db:
    image: <link>mysql:5.7</link>
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: <link>wordpress</link>
      MYSQL_USER: <link>wordpress</link>
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: <link>wordpress:latest</link>
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: <link>wordpress</link>
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: <link>wordpress</link>
    volumes:
      - wordpress_data:/var/www/html

  taincan:
    image: <link>taincan/taincan:latest</link>
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data: