version: "3"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - "/var/www/html:/var/www/html"
    links:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
  taincan:
    image: taincan/wordpress-plugin:latest
    depends_on:
      - wordpress
    links:
      - wordpress