version: '3.7'

services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_wordpress
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

  phpmyadmin:
    container_name: phpmyadmin    
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes: 
  db:
