version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads

  tainacan-installer:
    depends_on:
      - wordpress
    image: wordpress:cli
    volumes:
      - ./wp-content:/var/www/html/wp-content
    command: >
      /bin/bash -c "
        sleep 10 && \
        wp plugin install tainacan --activate --path=/var/www/html && \
        wp tainacan theme import /var/www/html/wp-content/plugins/tainacan/tainacan-theme/ --activate --path=/var/www/html && \
        wp rewrite structure '/%postname%/' --hard --path=/var/www/html
      "

volumes:
  db_data:
