name: Docker Compose Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f compose.yml up -d

    - name: Run tests
      run: docker-compose -f compose.yml exec -T web npm test

    - name: Tear down Docker Compose
      run: docker-compose -f compose.yml down
