name: WordPress Docker Compose Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Docker Compose
      run: docker-compose -f compose.yaml up -d
      
    - name: Run tests
      run: docker-compose -f compose.yaml exec -T web npm test

    - name: Tear down Docker Compose
      run: docker-compose -f compose.yaml down
