name: WordPress Docker Compose Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f compose.yaml up -d

    - name: Wait for services to initialize
      run: sleep 30s

    - name: Run tests
      run: curl -o http://localhost

    - name: Tear down Docker Compose
      run: docker-compose -f compose.yaml down
